### ISSUE TITLE
How to add anaconda/tensorflow to Maya

### ISSUE THREAD

**Issue by syedharoonalam** [dgovil/MLDeform#2]
Hi Dhruv, I am trying to run your repo but kind of stuck at bringing TensorFlow to Maya.

I first tried to install TensorFlow using mayapy, but using that I was getting attached error
![Untitled](https://user-images.githubusercontent.com/2439485/123262823-e4dd8e80-d52a-11eb-98a6-450f17767fa6.png)
It complains when imp.load_module('_pywrap_tensorflow_internal' but _pywrap_tensorflow_internal is present.

Anyway, I followed your advice and install tf2 using anaconda, but now I am not sure how to add anaconda library path to Maya library paths. I am guessing it should be conda/pkgs that I need to reference in Maya, but not sure where. Kindly advice.

OS: Linux/CentOS7
Maya Version: 2020

**Comment by syedharoonalam** [comment]
Hi @dgovil I tried adding PYTHONPATH+=/home/haroon/miniconda2/lib in Maya.env but Maya didn't pick TensorFlow library, I also added __init__.py in my google folder which is at /home/haroon/.local/lib/python2.7/site-packages/google
Please advise.

**Comment by dgovil** [comment]
As far as I know, Tensorflow has dropped support for Python 2, which makes it incompatible with Maya 2020. The existing python-2 versions may also have other incompatibilities with Maya.

This may work in Maya 2022 when using the Python 3 version but unfortunately I  haven't tried it yet since this code base hasn't worked in a while due to the differences in Maya Python support and Tensorflow.

**Comment by syedharoonalam** [comment]
Dhruv, Thank you for explaining this to me.
I am using your repo as a base for my academic project. So I will give it a go with either 2022 or 2018 as I think this repo demonstrates a very good use case of ML in Maya based on FDDA.

Do you still remember when you said in the other question regarding adding conda lib paths to go in maya lib paths,
which conda folders and maya env variables exactly were referring you to?

Just FYI, I am able to train the joints of the Cylinder model in collab, and the only part missing is Maya to pick tensorflow correctly to load output model. My crash when importing tensorflow from `mayapy pip install tensorflow` is attached, I think its just some prereq library (cudann, etc) is missing. So I was thinking if I can connect Maya with Anaconda, the problem will be solved. Thank you

[haroon_mayaCrash.txt](https://github.com/dgovil/MLDeform/files/6717671/haroon_mayaCrash.txt)

**Comment by syedharoonalam** [comment]
Thanks @dgovil for the suggestion, I switched to Maya 2022, and TensorFlow installed and loaded seamlessly in Maya.
I have also tested your deformer in 2022 with my (Collab) trained model and it loaded without any errors.
I will explore it further with different poses and let you know in case of any questions.

I am closing this issue for now. Thanks again!
